const customerList = [
    {
        id:1,
        firstName: 'obada',
        lastName: 'Alsayed',
        phoneNum: 958212992,
        email: 'obada@gmail.com',
        status: 'Not Linked',
        accountStatus: false,
        date: '5/5/2023',
    },
    {
        id:2,
        firstName: 'obada',
        lastName: 'Alsayed',
        phoneNum: 958212992,
        email: 'obada@gmail.com',
        status: 'Not Linked',
        accountStatus: false,
        date: '5/5/2023',
    },
    {
        id:3,
        firstName: 'obada',
        lastName: 'Alsayed',
        phoneNum: 958212992,
        email: 'obada@gmail.com',
        status: 'Not Linked',
        accountStatus: false,
        date: '5/5/2023',
    },
    {
        id:4,
        firstName: 'obada',
        lastName: 'Alsayed',
        phoneNum: 958212992,
        email: 'obada@gmail.com',
        status: 'Not Linked',
        accountStatus: false,
        date: '5/5/2023',
    },
    {
        id:5,
        firstName: 'obada',
        lastName: 'Alsayed',
        phoneNum: 958212992,
        email: 'obada@gmail.com',
        status: 'Not Linked',
        accountStatus: false,
        date: '5/5/2023',
    },
]
export default customerList