const contactList = [
  {
    id: 2001,
    firstName: 'Jubin Chawla',
    lastName: 'Lee',
    middleName: 'Jonathan',
    email: 'jubin.chawla@xyz.com',
    phoneNum: '+1-344432739',
    role: "Admin",
    accountStatus: true,
    image: '/assets/images/avatar/A1.jpg',
  },
  {
    id: 20013,
    firstName: 'Jubin Chawla',
    lastName: 'Lee',
    middleName: 'Jonathan',
    email: 'jubin.chawla@xyz.com',
    phoneNum: '+1-344432739',
    role: "User",
    accountStatus:true,
    image: '/assets/images/avatar/A1.jpg',
  },
  {
    id: 2002,
    firstName: 'Mark Johnson',
    lastName: 'Robert',
    middleName: 'Williams',
    email: 'mark.johnson@abc.com',
    phoneNum: '+1-34354234',
    accountStatus: true,
    role: "Admin",
    image: '/assets/images/avatar/A2.jpg',
  },
  // {
  //   id: 2003,
  //   firstName: 'Shane Lee',
  //   lastName: 'Vijay',
  //   middleName: 'Mark',
  //   email: 'shane.lee@mnz.com',
  //   phone: '+1-324563332',
  //   image: '/assets/images/avatar/A3.jpg',
  // },
  // {
  //   id: 2004,
  //   firstName: 'Chris Crains',
  //   lastName: 'Aulins',
  //   middleName: 'salah',
  //   email: 'chris.crains@cde.com',
  //   phone: '+1-233454323',
  //   image: '/assets/images/avatar/A4.jpg',
  // },
  // {
  //   id: 2005,
  //   firstName: 'Jonathan Trott',
  //   lastName: 'alsayed',
  //   middleName: 'salah',
  //   email: 'jonathan.trott@ewr.com',
  //   phone: '+1-324565345',
  //   image: '/assets/images/avatar/A5.jpg',
  // },
  // {
  //   id: 2006,
  //   firstName: 'Rohit Sharma',
  //   lastName: 'alsayed',
  //   middleName: 'salah',
  //   email: 'rohit.sharma@xcr.com',
  //   phone: '+1-435424345',
  //   image: '/assets/images/avatar/A6.jpg',
  // },
  // {
  //   id: 2007,
  //   firstName: 'Mark Lee',
  //   lastName: 'alsayed',
  //   middleName: 'salah',
  //   email: 'mark.lee@cdf.com',
  //   phone: '+1-989323434',
  //   image: '/assets/images/avatar/A7.jpg',
  // },
  // {
  //   id: 2008,
  //   firstName: 'Sain Williams',
  //   lastName: 'alsayed',
  //   middleName: 'salah',
  //   email: 'sain.williams@gww.com',
  //   phone: '+1-349848303',
  //   company: 'Eighth Exclusive Limited',
  //   image: '/assets/images/avatar/A8.jpg',
  // },
  // {
  //   id: 2009,
  //   firstName: 'Parth Aulins',
  //   lastName: 'alsayed',
  //   middleName: 'salah',
  //   email: 'parth.aulins@ddd.com',
  //   phone: '+1-4874387443',
  //   image: '/assets/images/avatar/A9.jpg',
  // },
  // {
  //   id: 2010,
  //   firstName: 'Rahul Bose',
  //   lastName: 'alsayed',
  //   middleName: 'salah',
  //   email: 'rahul.bose@xyz.com',
  //   phone: '+1-43235454',
  //   image: '/assets/images/avatar/A10.jpg',
  // },
  // {
  //   id: 2011,
  //   firstName: 'Rohan Bopanna',
  //   email: 'rohan.bopanna4@red.com',
  //   lastName: 'alsayed',
  //   middleName: 'salah',
  //   phone: '+1-432123345',
  //   image: '/assets/images/avatar/A11.jpg',
  // },
  // {
  //   id: 2012,
  //   firstName: 'Nikit Panwar',
  //   email: 'nikit.panwar@xyz.com',
  //   contact: '+1-542324563',
  //   company: 'International Exclusive Limited',
  //   isStarred: false,
  //   isFrequent: Math.random() > 0.5,
  //   label: 313,
  //   image: '/assets/images/avatar/A12.jpg',
  // },
  // {
  //   id: 2013,
  //   firstName: 'Vijay Murli',
  //   email: 'vijay.murli@xyz.com',
  //   contact: '+1-435432434',
  //   company: 'First Exclusive Limited',
  //   isStarred: false,
  //   isFrequent: Math.random() > 0.5,
  //   label: 311,
  //   image: '/assets/images/avatar/A13.jpg',
  // },
  // {
  //   id: 2014,
  //   name: 'David Boon',
  //   email: 'david.boon@xyz.com',
  //   contact: '+1-343322323',
  //   company: 'Second Exclusive Limited',
  //   isStarred: false,
  //   isFrequent: Math.random() > 0.5,
  //   label: 312,
  //   image: '/assets/images/avatar/A14.jpg',
  // },
  // {
  //   id: 2015,
  //   name: 'Saurabh Shukla',
  //   email: 'saurabh.shukla@sdd.com',
  //   contact: '+1-334354333',
  //   company: 'Seventh Exclusive Limited',
  //   isStarred: false,
  //   isFrequent: Math.random() > 0.5,
  //   label: 313,
  //   image: '/assets/images/avatar/A15.jpg',
  // },
  // {
  //   id: 2016,
  //   name: 'Nick Taylor',
  //   email: 'nick.taylor@usa.com',
  //   contact: '+1-432543345',
  //   company: 'Eighth Exclusive Limited',
  //   isStarred: true,
  //   isFrequent: Math.random() > 0.5,
  //   label: 312,
  //   image: '/assets/images/avatar/A15.jpg',
  // },
  // {
  //   id: 2017,
  //   name: 'Nikita Suman',
  //   email: 'nikita.suman@nicks.com',
  //   contact: '+91-3283828373',
  //   company: 'AXY Limited',
  //   isStarred: false,
  //   isFrequent: Math.random() > 0.5,
  //   label: 311,
  //   image: '/assets/images/avatar/A18.jpg',
  // },
  // {
  //   id: 2018,
  //   name: 'Laura Lohan',
  //   email: 'laura.lohan@laura.com',
  //   contact: '+1-3232323',
  //   company: 'US Exclusive Limited',
  //   isStarred: false,
  //   isFrequent: Math.random() > 0.5,
  //   label: 313,
  //   image: '/assets/images/avatar/A19.jpg',
  // },
  // {
  //   id: 2019,
  //   name: 'Jennifer John',
  //   email: 'jennifer.john@abc.com',
  //   contact: '+1-334354333',
  //   company: 'Seventh Exclusive Limited',
  //   isStarred: false,
  //   isFrequent: Math.random() > 0.5,
  //   label: 313,
  //   image: '/assets/images/avatar/A15.jpg',
  // },
  // {
  //   id: 2020,
  //   name: 'Robert Key',
  //   email: 'robert.key@key.com',
  //   contact: '+1-3289893323',
  //   company: 'UK Exclusive Limited',
  //   isStarred: false,
  //   isFrequent: Math.random() > 0.5,
  //   label: 313,
  //   image: '/assets/images/avatar/A20.jpg',
  // },
];
export default contactList;
